train:
  algorithm: "decisionTree"
  # "decisionTree", "randomForest", "adaBoost"

  decisionTree:
    maxDepth: 20
    maxNodes: 0
    nodeSize: 5

  randomForest:
    nTrees: 500
    mtry: 0
    maxDepth: 20
    maxNodes: 500
    nodeSize: 1
    subsample: 1.0
    classWeight: null
    seeds: null

  adaBoost:
    nTrees: 500
    maxDepth: 20
    maxNodes: 6
    nodeSize: 1

preProcessing:
  seed: 42
  testSize: 0.2
