train:
  algorithm: "logisticRegression"
  # "decisionTree", "randomForest", "adaBoost", "logisticRegression"

  decisionTree:
    maxDepth: 20
    maxNodes: 0
    nodeSize: 5

  randomForest:
    nTrees: 500
    mtry: 0
    maxDepth: 20
    maxNodes: 500
    nodeSize: 1
    subsample: 1.0
    classWeight: null
    seeds: null

  adaBoost:
    nTrees: 500
    maxDepth: 20
    maxNodes: 6
    nodeSize: 1

  logisticRegression:
    lambda: 0.0
    tol: 1E-5
    maxIter: 500

preProcessing:
  seed: 42
  testSize: 0.2
